imports:
    - { resource: config_dev.yml }

parameters:
    locale:  fr
    locales: [fr, en]

framework:
    test: ~
    csrf_protection:
        enabled: false
    session:
        storage_id: session.storage.mock_file
        gc_probability: 0
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        host: "mysql_test.%docker_name%"

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: cache/test
        local_upload:
            web_path:
                cache_prefix: cache/test/upload

#fos_elastica:
#    indexes:
#        search:
#            index_name: "%hostname%_test" # TODO
