imports:
    - { resource: config_dev.yml }

parameters:
    locale:  en
    locales: [en, fr]

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        connections:
            default:
                host:     "mysql_test.%dockername%"
                port:     3306
                dbname:   tstore_test
                user:     tstore_test
                password: tstore_test
    orm:
        auto_generate_proxy_classes: false

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: cache/test
        local_upload:
            web_path:
                cache_prefix: cache/test/upload
