imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: images.yml }
    - { resource: ekyna.yml }

framework:
    esi:        { enabled: true }
    translator: { fallbacks: ["%locale%"] }
    secret:      "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: false
    serializer:
        enabled: true
        enable_annotations: false
        name_converter: serializer.name_converter.camel_case_to_snake_case
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    #trusted_proxies: ['127.0.0.1', '10.0.0.0/8']
    trusted_proxies: ~
    session:
        handler_id:  snc_redis.session.handler
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  session.handler.native_file
        #save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        #gc_maxlifetime:  10800
        #cookie_domain:   "%router.request_context.host%"
        cookie_httponly: false # To false if setting session via XMLHttpRequest
        cookie_lifetime: 10800 # 3h
    fragments:       { path: /_fragment }
    http_method_override: true
    assets:
        version: '1.59'
        version_format: '%%s?v=%%s'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true

# Doctrine Cache Configuration
doctrine_cache:
    acl_cache:
        id: 'doctrine_cache.providers.acl_redis_provider'
    providers:
        acl_redis_provider:
            predis:
                host: "%redis.host%"
                port: "%redis.port%"

# Snc Redis Configuration
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%redis.host%"
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis.host%/1"
    session:
        client: default
    doctrine:
        query_cache:
            client: cache
            entity_manager: default
        result_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default

# HWI OAuth
hwi_oauth:
    firewall_names: ["front"]
    connect: ~
    fosub:
        username_iterations: 30
        properties:
            fake: fake
    resource_owners:
        # Report changes in :
        # - app/config/security.yml line 67: security.firewalls.front.oauth.resource_owners
        # - app/config/routing.yml (End of file "OAuth resource owners")
        google:
            type:           google
            client_id:      "%oauth.google.id%"
            client_secret:  "%oauth.google.secret%"
            scope:          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                display: page
                prompt: select_account
#        facebook:
#            type:           facebook
#            client_id:      "%oauth.facebook.id%"
#            client_secret:  "%oauth.facebook.secret%"
#            scope:          "email, public_profile"
#            infos_url:      "https://graph.facebook.com/me?fields=id,name,email"
#            options:
#                display: page

# FOS User Bundle
fos_user:
    from_email:
        address:     "%error_report_mail%"
        sender_name: Tablette Store

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport:  "%mailer_transport%"
            host:       "%mailer_host%"
            port:       "%mailer_port%"
            auth_mode:  "%mailer_auth_mode%"
            encryption: "%mailer_encryption%"
            username:   "%mailer_user%"
            password:   "%mailer_password%"
            spool:     { type: memory }
        report:
            transport:  "%mailer_transport%"
            host:       "%mailer_host%"
            port:       "%mailer_port%"
            auth_mode:  "%mailer_auth_mode%"
            encryption: "%mailer_encryption%"
            username:   "%mailer_user%"
            password:   "%mailer_password%"

# JMS I18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default
    cookie:
        enabled: false
    exclusion_pattern: "^/(admin|api)/"
    routers:
        - "router.default"
        - "ekyna_cms.router"
        - "ekyna_core.router"

# KNP Snappy
#knp_snappy:
#    pdf:
#        binary:  "%wkhtmltopdf_path%"
#    image:
#        binary:  "%wkhtmltoimage_path%"

# Swap
#florianv_swap:
#    providers:
#        fixer: ~
#        european_central_bank: ~
#        #google: ~
#        #yahoo: ~
