imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: images.yml }
    - { resource: ekyna.yml }

parameters:
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
    security.authentication.success_handler.class: Ekyna\Bundle\UserBundle\Authentication\AuthenticationSuccessHandler
    fos_elastica.client.class: Ekyna\Bundle\CoreBundle\Elastica\Client

framework:
    esi:        { enabled: true }
    translator: { fallback: "%locale%" }
    secret:      "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1', '10.0.0.0/8']
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_httponly: false # To false if setting session via XMLHttpRequest
        cookie_lifetime: 86400
        #cookie_domain:   "%router.request_context.host%"
        gc_maxlifetime:  86400
    fragments:       { path: /_fragment }
    http_method_override: true
    assets:
        version: '1.0'
        version_format: '%%s?v=%%s'
        base_path: /
        #base_urls: ["http://%hostname%", "https://%hostname%"]

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# KNP Snappy
#knp_snappy:
#    pdf:
#        binary:  "%wkhtmltopdf_path%"
#    image:
#        enabled: false

# JMS I18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default
    cookie:
        enabled: false
    exclusion_pattern: "^/(admin|api)/"
    routers:
        - "router.default"
        - "ekyna_cms.router"
        - "ekyna_core.router"
