imports:
    - { resource: config.yml }

services:
    validator.mapping.cache.apcu.cache:
        class: Doctrine\Common\Cache\ApcuCache
        calls:
            - [setNamespace, ["%validator.mapping.cache.prefix%"]]
    validator.mapping.cache.apcu:
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments:
            - "@validator.mapping.cache.apcu.cache"
    serializer.mapping.cache.apcu:
        class: Doctrine\Common\Cache\ApcuCache

framework:
    validation:
        cache: validator.mapping.cache.apcu
    serializer:
        cache: serializer.mapping.cache.apcu

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: apcu

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
