imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ekyna.yml }
    - { resource: images.yml }

parameters:
    #fos_elastica.client.class: Ekyna\Bundle\CoreBundle\Elastica\Client

framework:
    esi:        { enabled: true }
    translator: { fallback: "%locale%" }
    secret:      "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: false
    serializer:
        enabled: true
        enable_annotations: false
        name_converter: serializer.name_converter.camel_case_to_snake_case
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1', '10.0.0.0/8']
    session:
        handler_id:  snc_redis.session.handler
        cookie_httponly: false # To false if setting session via XMLHttpRequest
        cookie_lifetime: 86400
    fragments:       { path: /_fragment }
    http_method_override: true
    assets:
        version: '1.0'
        version_format: '%%s?v=%%s'
        base_path: /

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Doctrine Cache Configuration
doctrine_cache:
    acl_cache:
        id: 'doctrine_cache.providers.acl_redis_provider'
    providers:
        acl_redis_provider:
            predis:
                host: "%redis.host%"
                port: 6379

# Snc Redis Configuration
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%redis.host%"
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis.host%/1"
    session:
        client: default
    doctrine:
        query_cache:
            client: cache
            entity_manager: default
        result_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
#        metadata_cache:
#            client: cache
#            entity_manager: default
#    monolog:
#        client: cache
#        key: monolog
#    swiftmailer:
#        client: default
#        key: swiftmailer

# FOS User Bundle
fos_user:
    from_email:
        address:     "%error_report_mail%"
        sender_name: Sf Start

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# JMS I18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default
    cookie:
        enabled: false
    exclusion_pattern: "^/(admin|api)/"
    routers:
        - "router.default"
        - "ekyna_cms.router"
        - "ekyna_core.router"

# KNP Snappy
#knp_snappy:
#    pdf:
#        binary:  "%wkhtmltopdf_path%"
#    image:
#        enabled: false
