imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: images.yml }
    - { resource: ekyna.yml }

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1', '10.0.0.0/8']
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 86400
        #cookie_domain:   "%router.request_context.host%"
        gc_maxlifetime:  86400
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["WebBundle"]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        month: Ekyna\Bundle\CoreBundle\Dql\Month
                        year: Ekyna\Bundle\CoreBundle\Dql\Year
                        day: Ekyna\Bundle\CoreBundle\Dql\Day
                        rand: Ekyna\Bundle\CoreBundle\Dql\Rand
                        unix_timestamp: Ekyna\Bundle\CoreBundle\Dql\UnixTimestamp

# Doctrine Cache
doctrine_cache:
    providers:
        ekyna_settings:
            type: %cache%

# FOS Elastica
fos_elastica:
    serializer: ~
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            index_name: "%hostname%_%kernel.environment%"
            settings:
                index:
                    analysis:
                        filter:
                            fr_elision:
                                type: elision
                                articles: [l, m, t, qu, n, s, j, d, c, jusqu, quoiqu, lorsqu, puisqu]
                            fr_stop:
                                type: stop
                                stopwords: [_french_]
                                ignore_case: true
                            fr_stemmer:
                                type: stemmer
                                language: light_french
                        analyzer:
                            fr_index:
                                type: custom
                                tokenizer: standard
                                filter: [fr_elision, lowercase, fr_stop, fr_stemmer]
                            fr_search:
                                type: custom
                                tokenizer: standard
                                filter: [fr_elision, lowercase, fr_stop, fr_stemmer]

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            sortable: true

# KNP Gaufrette
knp_gaufrette:
    adapters:
        local_image:
            local:
                directory:  "%kernel.root_dir%/../media/image"
                create:     true
        local_file:
            local:
                directory:  "%kernel.root_dir%/../media/file"
                create:     true
    filesystems:
        local_image:
            adapter: local_image
        local_file:
            adapter: local_file
