ekyna_admin:
    dashboard:
        shortcuts:
            type: admin_shortcuts
            options:
                title: Raccourcis
#    resources:
#        app:
#            project:
#                entity: AppBundle\Entity\Project
#                repository: AppBundle\Entity\ProjectRepository
#                controller: AppBundle\Controller\Admin\ProjectController
#                form: AppBundle\Form\Type\ProjectType
#                table: AppBundle\Table\Type\ProjectType
#                translation:
#                    entity: AppBundle\Entity\ProjectTranslation
#                    fields: [title, summary, slug]
#                templates:
#                    "_form.html": "AppBundle:Admin/Project:_form.html"
#                    "show.html": "AppBundle:Admin/Project:show.html"
#    menus:
#        ekyna:
#            label: ekyna
#            icon: television
#            position: 10
#            entries:
#                projects:
#                    label: app.project.label.plural
#                    route: app_project_admin_home
#                    resource: app_project
#                    position: 0

ekyna_user:
    templates:
        email: 'WebBundle:Email:base.html.twig'
    account:
        enable: false
    notification:
        admin_login: false

ekyna_cms:
    home_route: app_page_home
    page:
        controllers:
            default:
                title: Par défault
                value: AppBundle:Page:default
        cookie_consent:
            enable: false
            controller: AppBundle:Page:default
        wide_search:
            enable: true
            controller: AppBundle:Page:search
    menu:
        roots:
            main:
                title: Menu principal
                description: Barre de navigation principale du site.
            footer:
                title: Pied de page
                description: Menu du pied de page.

ekyna_core:
    cache:
        default_smaxage: 21600 # 6h
        tag:
            secret: "%secret%"
            encode: true
    ui:
        google_font_url: "http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
        stylesheets:
            contents:
                - 'bundles/web/css/content.css'
#                - 'bundles/ekynacms/css/bootstrap-content.css'
        tinymce_formats_merge: true
#        tinymce_formats:
#            -
#                title: "Colors"
#                items:
#                    - {title: "Bordeau", selector : 'span,em,strong,p,h1,h2,h3,h4,h5,h6', inline: "span", classes: "bordeau"}
#                    - {title: "Vert", selector : 'span,em,strong,p,h1,h2,h3,h4,h5,h6', inline: "span", classes: "vert"}
#                    - {title: "Bleu", selector : 'span,em,strong,p,h1,h2,h3,h4,h5,h6', inline: "span", classes: "bleu"}
#                    - {title: "Orange", selector : 'span,em,strong,p,h1,h2,h3,h4,h5,h6', inline: "span", classes: "orange"}

#ekyna_social_buttons:
#    links:
#        github:
#            icon: github
#            url: http://github.com/ekyna/

ekyna_google:
    client:
        application_name: Test project
        developer_key: AIzaSyBQXhYai0pkg-ZhaBmP36372n1GZSw4qfo
        client_id: ""
        client_secret: ""
        redirect_uri: ""
