ekyna_admin:
    dashboard:
        shortcuts:
            type: admin_shortcuts
            options:
                title: Raccourcis
#    menus:
#        content:
#            label: app.example.title
#            icon: file
#            position: 10
#            entries:
#                example:
#                    route: app_example_admin_home
#                    label: app.example.label.plural
#                    resource: app.example

#ekyna_resource:
#    resources:
#        app:
#            example:
#                entity: AppBundle\Entity\Example
#                form: AppBundle\Form\Type\ExampleType
#                table: AppBundle\Table\Type\ExampleType

ekyna_user:
    notification:
        admin_login: false
    account:
        enable: true

ekyna_cms:
    home_route: app_page_home
    seo:
        no_follow: true
        no_index: true
        title_append: ' - start.dev'
    page:
        controllers:
            default:
                title: Par défault
                value: AppBundle:Page:default
                advanced: true
        cookie_consent:
            enable: true
            controller: AppBundle:Page:default
        wide_search:
            enable: true
            controller: AppBundle:Page:search
    menu:
        roots:
            main:
                title: Menu principal
                description: Barre de navigation principale du site.
            footer:
                title: Pied de page
                description: Menu du pied de page.
    slide_show:
        static:
            home: Accueil

ekyna_core:
    cache:
        enable: false
    ui:
        stylesheets:
            fonts:
                - 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700'
            contents:
                - 'bundles/web/css/content.css'
        colors:
            black:       1a1917
            white:       ffffff
            beige-light: f5f2f0
            beige:       ded8d1
            beige-dark:  ccc5bc
            orange:      ff6600
            primary:     154890
            secondary:   6699ff
            success:     5cb85c
            info:        5bc0de
            warning:     f0ad4e
            danger:      d9534f
        tinymce:
            base_formats: bootstrap
            custom_formats:
                -
                    title: 'Typography'
                    items:
                        -
                            title: 'Title'
                            items:
                                - {title: 'Hero', selector: 'h1,h2,h3,h4', classes: 'title-hero'}

#ekyna_commerce:
#    default:
#        company_logo: 'bundles/web/img/logo.svg'
#        country: 'FR'
#        currency: 'EUR'
#        customer:
#            birthday: false
#    pricing:
#        provider:
#            europa: true

#ekyna_social_buttons:
#    links:
#        github:
#            icon: github
#            url: http://github.com/ekyna/

ekyna_google:
    client:
        application_name: Test project
        developer_key: "%google.developer_key%"
        client_id: ~
        client_secret: ~
        redirect_uri: ~
