ekyna_admin:
    dashboard:
        shortcuts:
            type: admin_shortcuts
            options:
                title: Raccourcis
#    menus:
#        content:
#            label: app.example.title
#            icon: file
#            position: 10
#            entries:
#                example:
#                    route: app_example_admin_home
#                    label: app.example.label.plural
#                    resource: app.example

#ekyna_resource:
#    resources:
#        app:
#            example:
#                entity: AppBundle\Entity\Example
#                form: AppBundle\Form\Type\ExampleType
#                table: AppBundle\Table\Type\ExampleType

ekyna_user:
#    templates:
#        email: 'WebBundle:Email:base.html.twig'
    account:
        enable: true
#        register: true
#        resetting: true
#        profile: true
    notification:
        admin_login: false

ekyna_cms:
    home_route: app_page_home
    seo:
        no_follow: true
        no_index: true
        title_append: ' - start.dev'
    page:
        controllers:
            default:
                title: Par défault
                value: AppBundle:Page:default
        cookie_consent:
            enable: true
            controller: AppBundle:Page:default
        wide_search:
            enable: true
            controller: AppBundle:Page:search
    menu:
        roots:
            main:
                title: Menu principal
                description: Barre de navigation principale du site.
            footer:
                title: Pied de page
                description: Menu du pied de page.

ekyna_core:
    cache:
        default_smaxage: 21600 # 6h
        tag:
            secret: "%secret%"
            encode: true
    ui:
        stylesheets:
            fonts:
                - 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700'
            contents:
                - 'bundles/web/css/content.css'
        colors:
            primary: 337ab7
            success: 5cb85c
            info:    5bc0de
            warning: f0ad4e
            danger:  d9534f
        tinymce:
            base_formats: bootstrap
            custom_formats:
                -
                    title: 'Typography'
                    items:
                        -
                            title: 'Title'
                            items:
                                - {title: 'Blue', selector : 'h1,h2,h3,h4,h5,h6', styles: {color: 'blue'}}

#ekyna_social_buttons:
#    links:
#        github:
#            icon: github
#            url: http://github.com/ekyna/

ekyna_google:
    client:
        application_name: Test project
        developer_key: AIzaSyBQXhYai0pkg-ZhaBmP36372n1GZSw4qfo
        client_id: ""
        client_secret: ""
        redirect_uri: ""
