app:
    resource: "@AppBundle/Resources/config/routing.yml"

ekyna_cms:
    resource: "@EkynaCmsBundle/Resources/config/routing.yml"

ekyna_media:
    resource: "@EkynaMediaBundle/Resources/config/routing.yml"

ekyna_sitemap:
    resource: "@EkynaSitemapBundle/Resources/config/routing.yml"

ekyna_setting:
    resource: "@EkynaSettingBundle/Resources/config/routing.yml"

ekyna_user:
    resource: "@EkynaUserBundle/Resources/config/routing.yml"

ekyna_admin:
    resource: "@EkynaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ekyna_file_manager:
    resource: "@EkynaFileManagerBundle/Resources/config/routing.yml"
    prefix:   /filemanager

ekyna_core:
    resource: "@EkynaCoreBundle/Resources/config/routing.yml"
