security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    acl:
        connection: default
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:  ^/admin
            switch_user: true
            context:     user
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login-check
                always_use_default_target_path: false
                default_target_path: /admin/dashboard
                use_referer: true
            remember_me:
                key: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                #domain:   "%router.request_context.host%"
                remember_me_parameter: _remember_me
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
        front:
            switch_user: true
            context:     user
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /
                use_referer: true
            remember_me:
                key: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                #domain:   "%router.request_context.host%"
                remember_me_parameter: _remember_me
            logout:
                path: fos_user_security_logout
                target: /
            anonymous: true
    access_control:
        - { path: "^/account/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/account/login-check", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/account/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/account/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/account.*", role: IS_AUTHENTICATED_REMEMBERED }
        - { path: "^/admin/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin/login-check", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin.*", role: ROLE_ADMIN }
#        - { path: "^/admin.*", allow_if: "is_fully_authenticated() and has_role('ROLE_ADMIN')" }
