security:
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
    acl:
        connection: default
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:        pbkdf2
            hash_algorithm:   sha512
            encode_as_base64: true
            iterations:       1000
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:  ^/admin
            switch_user: true
            context:     user
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login-check
                always_use_default_target_path: false
                default_target_path: /admin/dashboard
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                #domain:   "%router.request_context.host%"
                remember_me_parameter: _remember_me
            logout:
                path: /admin/logout
                target: /admin/login
                invalidate_session: false
            anonymous: true
        front:
            switch_user: true
            context:     user
            form_login:
                success_handler: ekyna_user.security.authentication_success_handler
                failure_handler: ekyna_user.security.authentication_failure_handler
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                target_path_parameter: _target_path
                default_target_path: /
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                #domain:   "%router.request_context.host%"
                remember_me_parameter: _remember_me
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
                invalidate_session: false
            oauth:
                #success_handler: ekyna_commerce.security.oauth_authentication_success_handler
                resource_owners:
                    google: "/oauth/login/check-google"
#                    facebook: "/oauth/login/check-facebook"
                login_path:     fos_user_security_login
                failure_path:   fos_user_security_login
                oauth_user_provider:
                    service: ekyna_user.oauth.fos_provider
            anonymous: true
    access_control:
        - { path: "^/admin/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin/login-check", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/admin.*", role: ROLE_ADMIN }
