version: '2'

volumes:
    database_test:
        external:
            name: "${COMPOSE_PROJECT_NAME}-database-test"

services:
    php:
        image: ekyna/php7-fpm-dev:7.1.12
        depends_on:
            - mysql_test
        ports:
            - "9000:22"
        volumes:
            - ./php/dev/php.ini:/etc/php7/conf.d/90-custom.ini:ro
            - ./php/dev/xdebug.ini:/etc/php7/conf.d/xdebug.ini:ro
        environment:
            PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}.local"

    mysql:
        ports:
            - "9010:3306"

    mysql_test:
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_test"
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        working_dir: /root
        ports:
            - "9011:3306"
        volumes:
            - ./mysql/mysql_backup.sh:/root/backup.sh:ro
            - database_test:/var/lib/mysql:rw
            - ../../var/backup:/backup:rw
        logging:
            driver: "json-file"
            options: { max-size: "2m", max-file: "3" }
        networks:
            default:
                aliases:
                    - "mysql_test.${COMPOSE_PROJECT_NAME}"

#    mysql_migration:
#        ports:
#            - "9012:3306"

    elasticsearch:
        ports:
            - "9020:9200" # HTTP
#            - "9300:9300" # TCP

    se_hub:
        container_name: "${COMPOSE_PROJECT_NAME}_se_hub"
        image: selenium/hub:3.4.0
        ports:
            - "9030:4444"
        expose:
            - "4444"
    se_chrome:
        container_name: "${COMPOSE_PROJECT_NAME}_se_chrome"
        image: selenium/node-chrome-debug:3.4.0
        ports:
            # Port is used for VNC only (password is "secret")
            - "9031:5900"
            - "9032:5555"
        expose:
            - "5555"
        links:
            - se_hub:hub
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
